### ISSUE TITLE
AnimationController.forward() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by talski** [samuelhk0595/delayed_widget#1]
I'm getting some `AnimationController.forward() called after AnimationController.dispose()` errors when fast switching routes (web) that use delayed widget, I could fix it by checking if the animation controller was diposed before forwarding:
```dart
// it was
if (widget.enabled) animationController.forward();

// changed to
if (widget.enabled && !animationController.toString().contains("DISPOSED")) animationController.forward();
```

But I guess it must have a better way to check if it was disposed than `animationController.toString().contains("DISPOSED")`

**Comment by samuelhk0595** [comment]
Hi @talski , sorry for the late in answer you. I just published a new version . This bug was fixed and the package was migrated to null safety. Thanks for the support, you're awesome!

**Comment by talski** [comment]
Nice, thank you!
